Create a conda environment:

<code> conda create --name dlPyTorch </code>

Activate the conda environment:

<code> conda activate dlPyTorch </code>

In [1]:
import torch
print(torch.cuda.is_available())
print(torch.rand(2,2))

True
tensor([[0.2415, 0.2166],
        [0.5087, 0.4622]])


<code> torch.cuda.is_available() </code> 

Here, the above line should return **TRUE** : PyTorch detects Graphics card. 
                                   **FALSE**: Need to reverify the Cuda installation.

## Tensors

A simple scalar (e.g., 1) can be represented as a tensor of rank 0, a vector is rank 1, 
an n × n matrix is rank 2, and so on. In the previous example, we created a rank 2
tensor with random values by using torch.rand().

In [2]:
x = torch.tensor([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
x

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

We can change an element in a tensor by using standard Python indexing:

In [4]:
x[0][3]=9
x

tensor([[1, 0, 0, 9],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

A special creation of functions to generate particular types of tensors. In particular, ones() and zeroes() will generate tensors filled
with 1s and 0s, respectively:

In [8]:
y=torch.zeros(4,4)
z=torch.ones(4,4)

print(y)
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

We can do some mathematical operations of tensors, shown below:

In [11]:
print(y+z)
print(x+z)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[ 2.,  1.,  1., 10.],
        [ 1.,  2.,  1.,  1.],
        [ 1.,  1.,  2.,  1.],
        [ 1.,  1.,  1.,  2.]])


And if you have a tensor of rank 0 (a scalar), you can pull out the value with ***item()***:

In [12]:
torch.rand(1).item()

0.3582570552825928

Tensors can live in the CPU or on the GPU and can be copied between
devices by using the to() function:

In [17]:
cpu_tensor = x
cpu_tensor.device

device(type='cpu')

In [18]:
gpu_tensor = cpu_tensor.to("cuda")
gpu_tensor.device

device(type='cuda', index=0)

First, we often need to find the maximum item in a tensor as well as the
index that contains the maximum value (as this often corresponds to the
class that the neural network has decided upon in its final prediction). These
can be done with the ***max()*** and ***argmax()*** functions. We can also use
item() to extract a standard Python value from a 1D tensor.

In [22]:
p=torch.rand(3,3)
print(p)
print(p.max())
p.max().item()

tensor([[0.0614, 0.9679, 0.0642],
        [0.2081, 0.9603, 0.0657],
        [0.6201, 0.7256, 0.8734]])
tensor(0.9679)


0.9679139256477356

To change the type of a tensor; for example, from a
LongTensor to a FloatTensor. We can do this with ***to()***:

In [23]:
x.type()

'torch.LongTensor'

In [28]:
m=torch.tensor([[1,2],[3,4]]).to(dtype=torch.float32)
print(m)
m.type()

tensor([[1., 2.],
        [3., 4.]])


'torch.FloatTensor'